export const properties = [
  {
    id: "modern-villa-old-airport",
    title: "Modern Villa, Old Airport",
    price: "ETB 45,000 /mo",
    beds: 4,
    baths: 3,
    size: "350 m²",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVgURC1lpKm2NhTjoN7OKXfArljV4h3wLH6LpjWuPeGCTDtBV4kJ6qriA-GgEEHF6goYhJeqb-X1HUf1VAFWd3UGza05kHoGe5oin8TRXd4XbpTFnTYCD_yhWbtJvRw3xGH18_ymJt-97r6da6q_0I4Fi7xHoi5Yj8CB4Z_W5cmZx0S9tnPh2ZcqMF6zmzAB503SOjajS9edta0m4A1QiiqKhVLEpN3y9o1OzCZILWZefKYilnrTnmZvmQmpcWFj8hUaP_rQKBv34",
    tag: "Verified",
    location: "Old Airport, Addis Ababa",
    lat: 9.0021,
    lng: 38.7214,
    type: "Villa",
    furnishing: "Fully Furnished",
    rating: 4.9,
    reviewCount: 42,
    description: "A beautifully designed modern villa in the heart of Old Airport, featuring spacious rooms, a private garden, and 24/7 security. Perfect for families looking for comfort and safety.",
    amenities: ["WiFi", "Parking", "Security", "Garden", "Generator", "Water Tank"],
    videoUrl: null,
  },
  {
    id: "spacious-bungalow-bole",
    title: "Spacious Bungalow, Bole",
    price: "ETB 60,000 /mo",
    beds: 5,
    baths: 4,
    size: "2 Parking",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0EeJDohb-Y-fG5jl0JvchacLjGXSYKxJQ_Lsm74xhAr3GeVPK2Cb6MoifTfaU5VnXJhv7OwaJAvh9OW_0TDGAK6_bI0O-sU_-_ZbP75Qw2WnDclVfPrmeYlEFNvjNnqZ3z1uyXXVj486wfyCrxJNK5xzNHRUDvOoIwswYy4bjCr6wGZguGZcgARNNB8rh69u5gGzTCxau_iXfIygVW8UuF8E26CZd6QwajrWrotpwOgVe3gNXYOgB9ORMmKGsC6JlIIAyJObMu5U",
    location: "Bole, Addis Ababa",
    lat: 9.0054,
    lng: 38.7842,
    type: "Apartment",
    furnishing: "Semi-Furnished",
    rating: 4.7,
    reviewCount: 28,
    description: "A spacious bungalow in the vibrant Bole area with modern amenities, close to international schools, shopping centers, and restaurants.",
    amenities: ["WiFi", "Parking", "Security", "Gym", "Pool", "Balcony"],
    videoUrl: null,
  },
  {
    id: "garden-retreat-sarbet",
    title: "Garden Retreat, Sarbet",
    price: "ETB 35,000 /mo",
    beds: 3,
    baths: 2,
    size: "Big Yard",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDb6JVfIscuxpDpXY41W8u4msNauYJnhHhpGchHpF9_Znw-vuBj8leYM312fc8uhXapfNkWwQpR0A-6FT7dgffuTRaTIu-5hZKRHbSeKcU-_4nEx7VFmv-_Mxh7u0XQn4wqnRrmaZA-aCJd5ZC9alyuJcQ0_rm7Ba0f-g3Ir8Qmc9sLJIN9oHZ0tztXBZ-_nq_8sKJtxb0BPhLDqxeKAUs1PEbedCLbhvjWqFGZuIQvNxDkBmRakF1I1jE6F90GlviJJE2fHykwUnY",
    tag: "New Listing",
    location: "Sarbet, Addis Ababa",
    lat: 9.0012,
    lng: 38.7456,
    type: "Condominium",
    furnishing: "Unfurnished",
    rating: 4.5,
    reviewCount: 15,
    description: "A peaceful garden retreat in Sarbet with a large yard, ideal for families with children. Quiet neighborhood with easy access to main roads.",
    amenities: ["Garden", "Parking", "Water Tank", "Playground"],
    videoUrl: null,
  },
  {
    id: "luxury-apt-kazanchis",
    title: "Luxury Apt, Kazanchis",
    price: "ETB 55,000 /mo",
    beds: 3,
    baths: 2,
    size: "180 m²",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCiBb1NM5847S207x5huwwcuv5kBXN_PLmy0vBJsL_6S2MX6L6qsm2c3tYAXii6b7lXV4Za110Kl4nEdSMr3YicFtJszfIMEiPdfSa32dEQidLxQwB62HsCcTREM1Ph03G5i32bq0LNEcvf1JT-027aG_i6f__iQHlipspzOd8HIWFP1c-uOx9IR8csqo4GX_P01JYtsG2q3StVskMxRtAHtSq-n1f5SdtD01_OcQcxsoRtHWZ71rzNvizcbMM0ySLjbCtJE9WbT2Y",
    location: "Kazanchis, Addis Ababa",
    lat: 9.0203,
    lng: 38.7654,
    type: "Apartment",
    furnishing: "Fully Furnished",
    rating: 4.8,
    reviewCount: 36,
    description: "A luxury apartment in Kazanchis with stunning city views, modern kitchen, and premium finishes. Walking distance to business district.",
    amenities: ["WiFi", "Elevator", "Security", "Gym", "Generator", "Balcony"],
    videoUrl: null,
  },
  {
    id: "family-home-cmc",
    title: "Family Home, CMC",
    price: "ETB 40,000 /mo",
    beds: 4,
    baths: 3,
    size: "250 m²",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCba5ZphRpbXGDIK5FAj-MxG-cUqBFk3OfCyEKS2uZwRP0RcxNtIxH0qmyeMztLU4IVlmxmevPGSOxkz9d3d2NjqWzo7FsdyciWVAoxyA-kNK0zSIzWc5vCZBibD0NInrEE9elSVa5FSaQWwW4MqgldrAJWl28M1-cKXezHkfNW2-Jcsa9N3sk9_JrgehNLLcFGjSSe3CFvzijdFeOkzEnlEIp7lscFo0PztZXO8XONLHum0Q5PBLno2pKtFsGHx_IclSbYYpuk5TE",
    location: "CMC, Addis Ababa",
    lat: 9.0152,
    lng: 38.8234,
    type: "Villa",
    furnishing: "Semi-Furnished",
    rating: 4.6,
    reviewCount: 22,
    description: "A family-friendly home in CMC with spacious rooms, a large compound, and excellent access to schools and hospitals.",
    amenities: ["Parking", "Garden", "Security", "Water Tank", "Playground", "Generator"],
    videoUrl: null,
  },
  {
    id: "penthouse-meskel-square",
    title: "Penthouse, Meskel Square",
    price: "ETB 85,000 /mo",
    beds: 4,
    baths: 3,
    size: "320 m²",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAMM6XrLMSocX4QOeQRYoq0gyha06ggpgqYauKlnI1LLNUMey7yDXLjm3yVL2GJyFDxHhBTWVOZQczaj2dOWPeYyPkjj3rOk4Tve1SXVuofN3QnLzusQSi2KaN8BOKotftvebr5SXLP0Detj9HfU2rmgiJ-fb21ChQM3ZY-mrsP4ZuzzESF-tGhkm_0cFm8HlrRvk_b0XD6JLUmRgACb-hXV7Ew1Z-DqNuYf3-POZHuRQPskc3fkXdMxmdmzXV50GQdIekadOOF6BI",
    tag: "Premium",
    location: "Meskel Square, Addis Ababa",
    lat: 9.0110,
    lng: 38.7612,
    type: "Private Compound",
    furnishing: "Fully Furnished",
    rating: 5.0,
    reviewCount: 8,
    description: "An exclusive penthouse with panoramic views of Meskel Square and the city skyline. Premium furnishings throughout.",
    amenities: ["WiFi", "Elevator", "Security", "Gym", "Pool", "Rooftop Terrace", "Generator"],
    videoUrl: null,
  },
  {
    id: "studio-apt-megenagna",
    title: "Studio Apt, Megenagna",
    price: "ETB 18,000 /mo",
    beds: 1,
    baths: 1,
    size: "55 m²",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC3ZV9m6_Y_LZqqQDCcexhsL2gN5GMgnT_u4XBoRKz87AK3aOC3IA73QOrIa1lVetpo_3M1_S7Fxs7sd6WOXXw-Xiuv-l0jFiPZW_PtEJXzb2J3VQEFNw7STvYIT15QqRrR6Z1GyktwuUI0DI-W8OqEzXDHPDmHQqdouwrLkxhtsYGu7-Jbz4r5-6SkwzarmrbaG-9RK8EVB9KU9vghd5JOR_JfodxAWQtyosVls4S73bl9oTw_Xs1vu3JcwUDJ-j_n7V7Lkzo3_wI",
    tag: "Budget Friendly",
    location: "Megenagna, Addis Ababa",
    lat: 9.0185,
    lng: 38.7985,
    type: "Services",
    furnishing: "Fully Furnished",
    rating: 4.3,
    reviewCount: 19,
    description: "A cozy studio apartment near Megenagna roundabout. Ideal for young professionals, with easy access to public transport.",
    amenities: ["WiFi", "Security", "Elevator", "Laundry"],
    videoUrl: null,
  },
];

export const users = [
  {
    id: "u1",
    name: "Abebe Bekele",
    role: "renter",
    phone: "+251 911 223 344",
    email: "abebe@example.com",
    avatar: null,
    joinedDate: "January 2024",
  },
  {
    id: "o1",
    name: "Dawit Gebre",
    role: "owner",
    phone: "+251 922 556 677",
    email: "dawit@example.com",
    avatar: null,
    joinedDate: "September 2023",
    listedProperties: ["modern-villa-old-airport", "spacious-bungalow-bole"],
  },
  {
    id: "o2",
    name: "Selamawit Tadesse",
    role: "agent",
    phone: "+251 933 889 900",
    email: "selam@rentals.et",
    avatar: null,
    joinedDate: "November 2023",
    listedProperties: ["garden-retreat-sarbet", "luxury-apt-kazanchis"],
  }
];

export const reviews = [
  { id: "r1", targetId: "u1", author: "Dawit", rating: 5, comment: "Excellent renter, very punctual with payments.", date: "2024-03-15" },
  { id: "r2", targetId: "o1", author: "Alem", rating: 4, comment: "Great landlord, very responsive to maintenance requests.", date: "2024-02-10" },
  { id: "r3", targetId: "o1", author: "Samuel", rating: 5, comment: "Fair pricing and beautiful properties. Highly recommended!", date: "2024-04-01" },
  { id: "r4", targetId: "o2", author: "Hana", rating: 5, comment: "Very professional agent. Helped me find the perfect home in a week!", date: "2024-01-20" }
];
